/**
 * S3 storage — two buckets per the spec.
 *
 *   - storagePrivate:      all internal documents, invoices, GRN/DC PDFs,
 *                          QR labels, BOQ uploads, Tally XML exports,
 *                          MSME certificate PDF. Access is ONLY via 15-min
 *                          pre-signed URLs generated by Lambdas.
 *   - storageEmailAssets:  public bucket holding the company logo (and only
 *                          the logo) embedded in SES email templates.
 *                          No other content is public in this system.
 *
 * Both buckets have object-versioning enabled (done via post-synth override
 * in `amplify/custom/storage-hardening.ts` — not applied here because Amplify
 * Gen 2's `defineStorage` doesn't yet expose `versioned: true`).
 *
 * Path-level access rules below use Amplify's high-level storage access DSL.
 * Lambda-only paths (invoice-pdfs, msme/, tally-exports/, boq-uploads/ except
 * the authenticated create path) have NO cognito-group access at all — the
 * Lambda runs with an IAM role that has explicit s3:GetObject/PutObject on
 * the specific prefix, via `access.functionResource()` declarations.
 */
import { defineStorage } from "@aws-amplify/backend";

export const storagePrivate = defineStorage({
  name: "avInventoryPrivate",
  isDefault: true,
  access: (allow) => ({
    // --- Per-user profile photos + attachments ---
    "profile-photos/{entity_id}/*": [
      allow.entity("identity").to(["read", "write", "delete"]),
      allow.groups(["Admin"]).to(["read", "delete"]),
    ],

    // --- GRN / DC / PO documents ---
    "grn-pdfs/*": [
      allow.groups(["Admin", "Logistics"]).to(["read", "write"]),
      allow.groups(["Purchase", "Sales"]).to(["read"]),
    ],
    "vendor-invoices/*": [
      allow.groups(["Admin", "Logistics", "Purchase"]).to(["read", "write"]),
      allow.groups(["Sales"]).to(["read"]),
    ],
    "dc-pdfs/*": [
      allow.groups(["Admin", "Logistics"]).to(["read", "write"]),
      allow.groups(["Purchase", "Sales"]).to(["read"]),
    ],
    "po-pdfs/*": [
      allow.groups(["Admin", "Purchase"]).to(["read", "write"]),
      allow.groups(["Logistics", "Sales"]).to(["read"]),
    ],
    "qr-labels/*": [allow.authenticated.to(["read", "write"])],

    // --- BOQ uploads (Purchase only writes; everyone reads) ---
    "boq-uploads/*": [
      allow.groups(["Admin", "Purchase"]).to(["read", "write"]),
      allow.groups(["Logistics", "Sales"]).to(["read"]),
    ],

    // --- Tally XML exports (Admin only — financial data) ---
    "tally-exports/*": [allow.groups(["Admin"]).to(["read", "write"])],

    // --- Client invoices (Sales + Admin write; others read) ---
    "client-invoices/*": [
      allow.groups(["Admin", "Sales"]).to(["read", "write"]),
      allow.groups(["Logistics", "Purchase"]).to(["read"]),
    ],

    // --- MSME certificate (Admin only; attached to MSME notices) ---
    "msme/*": [allow.groups(["Admin"]).to(["read", "write"])],

    // --- Service ticket attachments ---
    "service-tickets/*": [
      allow.groups(["Admin", "Logistics"]).to(["read", "write"]),
      allow.authenticated.to(["read"]),
    ],

    // --- Unit images (damage photos, receipt photos) ---
    "unit-images/*": [
      allow.groups(["Admin", "Logistics"]).to(["read", "write"]),
      allow.authenticated.to(["read"]),
    ],

    // --- Bulk data exports / reports ---
    "reports/*": [allow.groups(["Admin"]).to(["read", "write"])],
  }),
});

export const storageEmailAssets = defineStorage({
  name: "avInventoryEmailAssets",
  isDefault: false,
  access: (allow) => ({
    // The company logo is the only public asset.
    // Versioning is enabled via post-synth override so logo changes don't
    // break historical SES template renders.
    "logo/*": [
      allow.guest.to(["read"]),
      allow.groups(["Admin"]).to(["read", "write", "delete"]),
    ],
  }),
});
